source 'https://rubygems.org'
gem 'telegram-bot-ruby', '0.4.1'
gem 'google-api-client', '0.9.pre3'
gem 'fastimage'
gem 'representable', '2.3.0'

gem 'bundler'
gem 'rake'
gem 'pry'
gem 'rubocop'
gem 'grape', '0.12.0'
gem 'bson', '~> 3.0'
gem 'unicorn', '4.7.0'
gem 'pg'
gem 'mandrill-api'
gem 'rack-cors'
gem 'algoliasearch'
gem 'wannabe_bool'
gem 'mini_magick'
gem 'mixpanel-ruby'
gem 'aws-sdk'
gem 'mimemagic'
