{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"501", :name_commune=>"Acoua", :population=>"4714", :mayor_lname=>"DAROUECHI", :mayor_fname=>"Ahmed", :mayor_gender=>"M", :mayor_bday=>"7/27/1969", :mayor_job_code=>"20", :mayor_job_name=>"Employés (secteur privé)"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"502", :name_commune=>"Bandraboua", :population=>"10132", :mayor_lname=>"BOURA", :mayor_fname=>"Soulaimana", :mayor_gender=>"M", :mayor_bday=>"8/16/1977", :mayor_job_code=>"48", :mayor_job_name=>"Fonctionnaires de catégorie B"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"503", :name_commune=>"Bandrele", :population=>"7885", :mayor_lname=>"MOUSSA BEN", :mayor_fname=>"Ali Moussa", :mayor_gender=>"M", :mayor_bday=>"3/29/1966", :mayor_job_code=>"52", :mayor_job_name=>"Employés (autres entrep. publiques)"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"504", :name_commune=>"Bouéni", :population=>"6402", :mayor_lname=>"ABDOURAHAMAN", :mayor_fname=>"Mouslim", :mayor_gender=>"M", :mayor_bday=>"3/11/1977", :mayor_job_code=>"47", :mayor_job_name=>"Fonctionnaires de catégorie A"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"505", :name_commune=>"Chiconi", :population=>"7048", :mayor_lname=>"ANTOYISSA", :mayor_fname=>"Zainoudine", :mayor_gender=>"M", :mayor_bday=>"8/11/1970", :mayor_job_code=>"43", :mayor_job_name=>"Enseignants 1er deg.-directeurs école"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"506", :name_commune=>"Chirongui", :population=>"8047", :mayor_lname=>"IBRAHIMA", :mayor_fname=>"Hanima", :mayor_gender=>"F", :mayor_bday=>"4/27/1968", :mayor_job_code=>"47", :mayor_job_name=>"Fonctionnaires de catégorie A"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"507", :name_commune=>"Dembeni", :population=>"10923", :mayor_lname=>"HAMADA", :mayor_fname=>"Soihibou", :mayor_gender=>"M", :mayor_bday=>"8/7/1974", :mayor_job_code=>"11", :mayor_job_name=>"Entrepreneurs en batiments"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"509", :name_commune=>"Kani-Kéli", :population=>"4920", :mayor_lname=>"AHMED", :mayor_fname=>"Soilihi", :mayor_gender=>"M", :mayor_bday=>"1/1/1955", :mayor_job_code=>"43", :mayor_job_name=>"Enseignants 1er deg.-directeurs école"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"511", :name_commune=>"Mamoudzou", :population=>"57281", :mayor_lname=>"MAJANI", :mayor_fname=>"Mohamed", :mayor_gender=>"M", :mayor_bday=>"6/15/1961", :mayor_job_code=>"57", :mayor_job_name=>"Sans profession déclarée"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"512", :name_commune=>"Mtsamboro", :population=>"7805", :mayor_lname=>"COLO", :mayor_fname=>"Harouna", :mayor_gender=>"M", :mayor_bday=>"3/16/1978", :mayor_job_code=>"42", :mayor_job_name=>"Professeurs du secondaire et techn."}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"513", :name_commune=>"M'Tsangamouji", :population=>"6314", :mayor_lname=>"IBRAHIMA", :mayor_fname=>"Said Maanrifa", :mayor_gender=>"M", :mayor_bday=>"10/30/1974", :mayor_job_code=>"5", :mayor_job_name=>"Industriels-Chefs entreprise"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"514", :name_commune=>"Ouangani", :population=>"9834", :mayor_lname=>"AHMED-COMBO", :mayor_fname=>"Ali", :mayor_gender=>"M", :mayor_bday=>"3/18/1973", :mayor_job_code=>"43", :mayor_job_name=>"Enseignants 1er deg.-directeurs école"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"515", :name_commune=>"Pamandzi", :population=>"9892", :mayor_lname=>"SAIDALI", :mayor_fname=>"Mahafourou", :mayor_gender=>"M", :mayor_bday=>"8/5/1971", :mayor_job_code=>"47", :mayor_job_name=>"Fonctionnaires de catégorie A"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"516", :name_commune=>"Sada", :population=>"10195", :mayor_lname=>"BAMANA", :mayor_fname=>"Anchya", :mayor_gender=>"F", :mayor_bday=>"3/12/1971", :mayor_job_code=>"47", :mayor_job_name=>"Fonctionnaires de catégorie A"}
{:code_departement=>"ZM", :name_departement=>"MAYOTTE", :num_commune=>"517", :name_commune=>"Tsingoni", :population=>"10454", :mayor_lname=>"MOHAMED", :mayor_fname=>"Bacar", :mayor_gender=>"M", :mayor_bday=>"6/22/1968", :mayor_job_code=>"47", :mayor_job_name=>"Fonctionnaires de catégorie A"}
{:code_departement=>"ZS", :name_departement=>"SAINT PIERRE ET MIQUELON", :num_commune=>"502", :name_commune=>"Saint-Pierre", :population=>"5676", :mayor_lname=>"CLAIREAUX", :mayor_fname=>"Karine", :mayor_gender=>"F", :mayor_bday=>"11/15/1963", :mayor_job_code=>"49", :mayor_job_name=>"Fonctionnaires de catégorie C"}
